### ISSUE TITLE
circuit diagram

### ISSUE THREAD

**Issue by S-Manasa** [animikhaich/Facial-recognition-based-automatic-door-lock-unlock-system#1]
Hey,
I am not able to find the circuit diagram for the connections.
Can i get the link or the circuit diagram?

**Comment by animikhaich** [comment]
There is no circuit diagram for this build. This was a very small and easy project. 
The hardware implementation is rudimentary and it basically works by connecting the Arduino to the laptop and then connecting the motor to Arduino.
The hardware was attached just for demonstration purposes and contains no complicated connections. 
You can find the pin numbers and/or modify them in the Arduino program code file.
It's just a simple Vdd and gnd connection for the DC motor.
